#!/bin/bash

# Call the first script to fetch the data
chmod +x apiAutomation-0x00
./apiAutomation-0x00

# Check if the data.json file exists and is not empty before proceeding
if [ ! -s data.json ]; then
    echo "Error: The data file 'data.json' could not be created or is empty. Exiting."
    exit 1
fi

# Process the fetched data
name=$(jq -r '.name' data.json | sed 's/\b\(.\)/\u\1/g')
weight=$(jq -r '.weight' data.json)
height=$(jq -r '.height' data.json)
types=$(jq -r '.types[].type.name' data.json | sed 's/\b\(.\)/\u\1/g' | sed ':a;N;$!ba;s/\n/, /g')

formatted_height=$(awk "BEGIN { printf \"%.1f\", ${height}/10 }" < /dev/null)

echo "$name is of type $type, weighs ${formatted_weight}kg, and is ${formatted_height}m tall."

# Optional: Clean up the temporary file
# rm data.json
