#!/bin/bash

name=$(jq -r '.name' data.json | sed 's/\b\(.\)/\u\1/g')
weight=$(jq -r '.weight' data.json)
height=$(jq -r '.height' data.json)
types=$(jq -r '.types[].type.name' data.json | sed 's/\b\(.\)/\u\1/g' | sed ':a;N;$!ba;s/\n/, /g')

formatted_height=$(awk "BEGIN { printf \"%.1f\", ${height}/10 }")

echo "${name} is of type ${types}, weighs ${weight}kg, and is ${formatted_height}m tall."